import { ShieldCheck } from 'lucide-react';
import { defineModule } from '@/app/define-module';
import { useOpenSecurityAlertsCount } from './SecuritePage';

export default defineModule({
  id: 'a-plateforme-securite',
  nav: {
    group: 'plateforme',
    label: 'Plateforme & sécurité',
    icon: <ShieldCheck />,
    order: 100,
    badge: useOpenSecurityAlertsCount,
    keywords: [
      'paramètres',
      'réglages',
      'identité',
      'régional',
      'marchés',
      'pays',
      'devises',
      'tva',
      'fonctionnalités',
      'interrupteurs',
      'connexions',
      'stripe',
      'brevo',
      'maps',
      'caisse',
      'traduction',
      'azure translator',
      'langues',
      'multilingue',
      'cartographie',
      'google maps',
      'flotte',
      'position',
      'geocoding',
      'administrateurs',
      'rôles',
      'permissions',
      'double authentification',
      'totp',
      'mfa',
      'sessions',
      'audit',
      'journal',
      'fraude',
      'liste de blocage',
      'cgu',
      'cgv',
      'rgpd',
      'anonymisation',
      'conservation',
      'santé',
      'maintenance',
      'incidents',
      'versions',
      'sauvegardes',
      'corbeille',
      'export firestore',
    ],
  },
  permission: 'platform.access',
  routes: [
    { path: 'plateforme', lazy: () => import('./ParametresPage').then((m) => ({ Component: m.ParametresPage })) },
    { path: 'plateforme/parametres', lazy: () => import('./ParametresPage').then((m) => ({ Component: m.ParametresPage })) },
    { path: 'plateforme/marches', lazy: () => import('./MarchesPage').then((m) => ({ Component: m.MarchesPage })) },
    { path: 'plateforme/fonctionnalites', lazy: () => import('./FonctionnalitesPage').then((m) => ({ Component: m.FonctionnalitesPage })) },
    { path: 'plateforme/connexions', lazy: () => import('./ConnexionsPage').then((m) => ({ Component: m.ConnexionsPage })) },
    { path: 'plateforme/traduction', lazy: () => import('./TraductionPage').then((m) => ({ Component: m.TraductionPage })) },
    { path: 'plateforme/cartographie', lazy: () => import('./CartographiePage').then((m) => ({ Component: m.CartographiePage })) },
    { path: 'plateforme/administrateurs', lazy: () => import('./AdministrateursPage').then((m) => ({ Component: m.AdministrateursPage })) },
    { path: 'plateforme/securite', lazy: () => import('./SecuritePage').then((m) => ({ Component: m.SecuritePage })) },
    { path: 'plateforme/journal', lazy: () => import('./JournalPage').then((m) => ({ Component: m.JournalPage })) },
    { path: 'plateforme/fraude', lazy: () => import('./FraudePage').then((m) => ({ Component: m.FraudePage })) },
    { path: 'plateforme/legal-rgpd', lazy: () => import('./LegalRgprPage').then((m) => ({ Component: m.LegalRgprPage })) },
    { path: 'plateforme/sante', lazy: () => import('./SanteMaintenancePage').then((m) => ({ Component: m.SanteMaintenancePage })) },
    { path: 'plateforme/donnees', lazy: () => import('./DonneesPage').then((m) => ({ Component: m.DonneesPage })) },
  ],
});
