// Permissions de l'équipe interne (super admin). Chaque permission suit la forme
// « domaine.action » ; les actions reprennent le cahier : voir, modifier,
// rembourser, exporter, supprimer. La matrice ci-dessous sert d'amorçage à la
// collection `adminRoles` ; les règles de sécurité lisent `admins/{uid}.permissions`.
import type { AdminRole } from '../constants/enums';
import type { Cents } from '../pricing/money';

export const ADMIN_PERMISSIONS = [
  'dashboard.view',
  'search.use',
  'analytics.view',
  'reports.view',
  'reports.schedule',
  'exports.run',
  // Restaurants
  'restaurants.view',
  'restaurants.edit',
  'restaurants.validate',
  'restaurants.suspend',
  'restaurants.delete',
  'restaurants.commercial',
  'restaurants.impersonate',
  'restaurants.bulk',
  'restaurants.import',
  // Livreurs
  'drivers.view',
  'drivers.edit',
  'drivers.validate',
  'drivers.sanction',
  'drivers.pay_rules',
  'drivers.bulk',
  // Clients
  'customers.view',
  'customers.edit',
  'customers.block',
  'customers.delete',
  'customers.credit',
  /** Coordonnées complètes et données bancaires non masquées. */
  'personal_data.view',
  // Commandes et règles
  'orders.view',
  'orders.intervene',
  'order_rules.edit',
  'zones.edit',
  'display.edit',
  // Avis et support
  'reviews.view',
  'reviews.moderate',
  'support.view',
  'support.handle',
  'support.escalate',
  'support.configure',
  // Argent
  'payments.view',
  'payments.configure',
  'refunds.create',
  'refunds.approve',
  'finance.view',
  'finance.payouts',
  'finance.adjust',
  'finance.hold',
  'invoices.view',
  'invoices.issue',
  'tax.reports',
  'plans.edit',
  'commissions.edit',
  'subscriptions.manage',
  // Croissance
  'promotions.view',
  'promotions.edit',
  'loyalty.edit',
  'notifications.send',
  'templates.edit',
  'announcements.edit',
  'crm.view',
  'crm.edit',
  'crm.manage_team',
  // Plateforme, sécurité, conformité
  /** Accès à la rubrique (menu visible) : accordée dès qu'un rôle a un droit plateforme, même partiel. */
  'platform.access',
  'settings.view',
  'settings.edit',
  'markets.edit',
  'features.edit',
  'integrations.view',
  'integrations.edit',
  'admins.view',
  'admins.manage',
  'audit.view',
  'security.manage',
  'fraud.view',
  'fraud.manage',
  'legal.edit',
  'gdpr.handle',
  'system.view',
  'system.manage',
  'trash.view',
  'trash.restore',
  'backups.manage',
] as const;

export type AdminPermission = (typeof ADMIN_PERMISSIONS)[number];

const VIEW_BASE: readonly AdminPermission[] = ['dashboard.view', 'search.use'];

/** Permissions par défaut de chaque rôle interne. */
export const DEFAULT_ADMIN_ROLE_PERMISSIONS: Record<AdminRole, readonly AdminPermission[]> = {
  super_admin: ADMIN_PERMISSIONS,
  support: [
    ...VIEW_BASE,
    'restaurants.view',
    'drivers.view',
    'customers.view',
    'customers.block',
    'customers.credit',
    'orders.view',
    'orders.intervene',
    'reviews.view',
    'reviews.moderate',
    'support.view',
    'support.handle',
    'support.escalate',
    'refunds.create',
    'payments.view',
    'platform.access',
    'fraud.view',
    'gdpr.handle',
    'trash.view',
  ],
  finance: [
    ...VIEW_BASE,
    'analytics.view',
    'reports.view',
    'reports.schedule',
    'exports.run',
    'restaurants.view',
    'restaurants.commercial',
    'drivers.view',
    'drivers.pay_rules',
    'customers.view',
    'personal_data.view',
    'orders.view',
    'payments.view',
    'payments.configure',
    'refunds.create',
    'refunds.approve',
    'finance.view',
    'finance.payouts',
    'finance.adjust',
    'finance.hold',
    'invoices.view',
    'invoices.issue',
    'tax.reports',
    'plans.edit',
    'commissions.edit',
    'subscriptions.manage',
    'promotions.view',
    'platform.access',
    'fraud.view',
    'audit.view',
  ],
  sales: [
    ...VIEW_BASE,
    'analytics.view',
    'restaurants.view',
    'restaurants.edit',
    'restaurants.import',
    'restaurants.commercial',
    'orders.view',
    'promotions.view',
    'promotions.edit',
    'crm.view',
    'crm.edit',
    'subscriptions.manage',
    'announcements.edit',
  ],
  ops: [
    ...VIEW_BASE,
    'analytics.view',
    'reports.view',
    'exports.run',
    'restaurants.view',
    'restaurants.edit',
    'restaurants.validate',
    'restaurants.suspend',
    'restaurants.impersonate',
    'restaurants.bulk',
    'drivers.view',
    'drivers.edit',
    'drivers.validate',
    'drivers.sanction',
    'drivers.bulk',
    'customers.view',
    'orders.view',
    'orders.intervene',
    'order_rules.edit',
    'zones.edit',
    'display.edit',
    'reviews.view',
    'reviews.moderate',
    'support.view',
    'refunds.create',
    'promotions.view',
    'notifications.send',
    'announcements.edit',
    'platform.access',
    'settings.view',
    'features.edit',
    'integrations.view',
    'system.view',
    'fraud.view',
    'fraud.manage',
    'trash.view',
    'trash.restore',
  ],
  city_manager: [
    ...VIEW_BASE,
    'analytics.view',
    'reports.view',
    'restaurants.view',
    'restaurants.edit',
    'restaurants.validate',
    'restaurants.suspend',
    'drivers.view',
    'drivers.edit',
    'drivers.validate',
    'drivers.sanction',
    'customers.view',
    'orders.view',
    'orders.intervene',
    'zones.edit',
    'display.edit',
    'reviews.view',
    'support.view',
    'refunds.create',
    'promotions.view',
    'promotions.edit',
    'notifications.send',
    'crm.view',
    'crm.edit',
  ],
};

/** Plafond de remboursement sans validation par rôle (centimes). */
export const DEFAULT_REFUND_LIMITS: Record<AdminRole, Cents> = {
  super_admin: Number.MAX_SAFE_INTEGER,
  support: 5_000,
  finance: 50_000,
  sales: 0,
  ops: 10_000,
  city_manager: 5_000,
};

/** Rôles dont l'affichage des coordonnées et données bancaires est masqué. */
export const ROLES_WITH_MASKED_DATA: readonly AdminRole[] = ['support', 'sales', 'ops', 'city_manager'];

/** Rôles limités à leur périmètre géographique (villes de `admins.cityIds`). */
export const CITY_SCOPED_ROLES: readonly AdminRole[] = ['city_manager'];

export function adminHasPermission(
  admin: { role: AdminRole; permissions: readonly AdminPermission[]; active: boolean },
  permission: AdminPermission,
): boolean {
  if (!admin.active) return false;
  return admin.role === 'super_admin' || admin.permissions.includes(permission);
}
